require "fpm/namespace"
require "fpm/builder"

require "fpm/package/dir"
require "fpm/package/gem"
require "fpm/package/rpm"
#require "fpm/target/deb"
#require "fpm/target/rpm"
#require "fpm/target/solaris"
#require "fpm/target/puppet"

#require "fpm/source"
#require "fpm/source/dir"
#require "fpm/source/gem"
#require "fpm/source/pear"
#require "fpm/source/python"
#require "fpm/source/rpm"
#require "fpm/source/tar"
